In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]

x_data = torch.tensor(data) # data -> tensor 

np_array = np.array(data) # data -> np array
x_np = torch.from_numpy(np_array) # np array -> tensor

In [3]:
x_ones = torch.ones_like(x_data) # x_data의 shape를 유지하면서 모든 원소의 값이 1인 텐서 생성
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 shape를 유지하면서 모든 원소의 값이 0~1 사이의 난수인 텐서 생성
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9672, 0.2046],
        [0.5538, 0.0636]]) 



In [4]:
shape = (2,3,) # 2*3 행렬 생각하면 됨
rand_tensor = torch.rand(shape) # 2*3 크기의 텐서 생성. 각 원소는 난수
ones_tensor = torch.ones(shape) # 2*3 크기의 텐서 생성. 각 원소는 1
zeros_tensor = torch.zeros(shape) # 2*3 크기의 텐서 생성. 각 원소는 0

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7493, 0.9541, 0.2144],
        [0.0562, 0.5101, 0.3183]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(3,4) # 3*4 크기의 텐서 생성. 각 원소는 난수

print(f"Shape of tensor: {tensor.shape}") # 3*4 츨력
print(f"Datatype of tensor: {tensor.dtype}") # 각 원소의 자료형
print(f"Device tensor is stored on: {tensor.device}") # 텐서가 저장된 곳

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

텐서 연산

In [6]:
tensor = torch.ones(4, 4) # 1로 이루어진 4*4 텐서
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0 # 두 번째 col을 0으로 : [1 0 1 1]
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # concat. dim = 1이니까 오른쪽으로 concat된다. dim=0이면 밑으로 concat
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T # T = transpose
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor) # tensor와 같은 사이즈에 난수로 이루어진 텐서를 생성
torch.matmul(tensor, tensor.T, out=y3) # tensor.matmul(tensor.T)을 y3에 저장

print(y1)
print(y2)
print(y3)
print()

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# 텐서에 있는 숫자를 모두 더한다. 텐서플로우의 reduce_sum과 같다.
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [18]:
# 연산 결과를 피연산자에 저장(num = num + 1과 같이). 사용을 권장하지 않는다고 한다.
print(tensor, "\n")
tensor.add_(5) # 각 원소에 5를 더한다
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


tensor <-> np array

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# t에 1을 더하면 n도 역시 그 결과가 반영된다. 헐?
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [22]:
# np array -> tensor
n = np.ones(5) # [1 1 1 1 1]
t = torch.from_numpy(n)

# n에 1을 더하면 t도 역시 그 결과가 반영된다. n과 t는 한몸이라 생각하면 될듯. '내보내기'했다 생각하면 큰일나겠다.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
